### ISSUE TITLE
Add some pics to the website or the README?

### ISSUE THREAD

**Issue by torchsmith** [astrolicious/studiocms#17]
I'd love to see what this looks like or has to offer through the UI interface without needing to clone and install the repo.

**Comment by Adammatthiesen** [comment]
Hi, we do have a live-demo https://demo.astro-studiocms.xyz and we are actively working on trying to more of the repo flushed out, please bear with us as we did just make our code-base public yesterday!

**Comment by torchsmith** [comment]
I saw that demo, but I'm talking about the backend, not the frontend.

**Comment by dreyfus92** [comment]
Hello @torchsmith, thanks for bringing this up. I think that it would be better to add this in the upcoming docs website we will be working on soon.
